#! /bin/bash
# by k.deiss@it-userdesk.de
# V 0.0.1.9.10.14
# V 0.0.2.28.3.15
# V 0.0.3.28.12.15
# V 0.1.0.21.9.20 Update to Linux Mint 20

AQ="/opt/AmutaQ!"
if [ -d $AQ ];then
    echo "AmutaQ! folder found, fine!"
else
    echo "$AQ not found! Pls install binary package before running this script!"
    exit 1
fi


echo "preparing machine ....."
apt-get update
apt-get install ssh mc nfs-kernel-server htop sshpass dos2unix #open-vm-tools-desktop
apt-get install perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions #python python-paramiko python-setuptools 
apt-get install xfsdump xfsprogs libmhash2 libfuse2 build-essential libmhash-dev libfuse-dev pkg-config
apt-get install libarchive-zip-perl cryptsetup swaks

/usr/bin/rsync -rlKtzuv "./root/" "/"
#sudo update-rc.d ddumbfs defaults
systemctl daemon-reload
systemctl enable ddumbfs

echo "press key"
read line

#xrdp
apt install xrdp

##Kein Webmin! Sicherheitslücken? ah
#dpkg -i /opt/AmutaQ!-install/webmin/webmin_1.700_all.deb

echo "press key"
read line


#der ganze kack fuer smime
update-desktop-database /home/dasi/.local/share/applications
update-mime-database /home/dasi/.local/share/mime

echo "press key"
read line

./filepatch
./set_rights

echo "install vmware vix-disklib-lib"
echo "press key"
read line
/opt/AmutaQ!-install/vmware-vix-disklib-distrib/vmware-install.pl

echo "dont forget to open ssh port on your esxi server !!!!!!!!!"
echo "press key"
read line
