#! /bin/bash
# by k.deiss@it-userdesk.de
# V 0.0.1.9.10.14
# V 0.0.2.28.3.15
# V 0.0.3.28.12.15
# V 0.1.0.21.9.20 Update to Linux Mint 20
# V 0.1.0.30.9.22 Update for Linux Mint 20.1


AQI="/opt/AmutaQ-installer"
AQ="/opt/AmutaQ!"

if [ -d $AQI ];then
    echo "AmutaQ! Installer folder '$AQI' found, fine!"
else
    echo "Folder '$AQI' not found! Run this script from '$AQI'"
    exit 1
fi

if [ -d $AQ ];then
    echo "AmutaQ! folder '$AQ' found, fine!"
else
    echo "$AQ not found! Try to install AmutaQ via git!"
    apt-get -y install git
    git clone https://github.com/kdeiss/AmutaQ.git $AQ
    if [ -d $AQ ];then
	echo "AmutaQ! folder '$AQ' found, fine!"
    else
        echo "Folder '$AQ' not found! Pls run 'git clone https://github.com/kdeiss/AmutaQ.git $AQ' before running this script!"
	exit 1
    fi
fi


function install_webmin()
{	apt-get -y install perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python unzip shared-mime-info
	wget https://prdownloads.sourceforge.net/webadmin/webmin_2.000_all.deb
	dpkg --install webmin_2.000_all.deb
	rm -f ./webmin_2.000_all.deb
	systemctl start webmin
}

function ask4webmin()
{	let INSTALL_WEBMIN=0
	echo ""
	while true; do
	    read -p "Do you wish to install webmin? [y/n] " yn
	    case $yn in
    		[Yy]* ) let INSTALL_WEBMIN=1; break;;
    		[Nn]* ) break;;
    		* ) echo "Please answer yes or no.";;
	    esac
	done
}


ask4webmin


echo "INF Installing required packages."
apt-get update
apt-get install -y ssh mc nfs-kernel-server htop sshpass dos2unix #open-vm-tools-desktop
apt-get install -y perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions #python python-paramiko python-setuptools
apt-get install -y xfsdump xfsprogs libmhash2 libfuse2 build-essential libmhash-dev libfuse-dev pkg-config
apt-get install -y libarchive-zip-perl cryptsetup swaks
#xrdp
apt-get install -y xrdp xorgxrdp

echo ""
echo "all required packages installed - now installing binaries!"

/usr/bin/rsync -rlKtzuv "$AQI/INSTALL/root/" "/"

echo ""
echo "binaries installed - enabling DDUMBFS service!"


#sudo update-rc.d ddumbfs defaults
systemctl daemon-reload
systemctl enable ddumbfs

echo ""
echo "DDUMBFS service enabled!"

##Webmin optional! 

if [ $INSTALL_WEBMIN -eq 1 ] ; then
    install_webmin
    echo ""
    echo "webmin service installed - access it at http://localhost:10000"
    echo "press key"
    read line
fi

#smime&co
update-desktop-database /home/dasi/.local/share/applications
update-mime-database /home/dasi/.local/share/mime

echo ""
echo "Desktop and MIME update succeeded - will patch the system now!"
echo "NOTE: Each required file will be loaded into your favorite editor after patching."
echo "Customize settings to suit your needs."
echo "press key"
read line


$AQI/INSTALL/filepatch

echo ""
echo "system patched - granting rights!"

$AQI/INSTALL/set_rights

echo ""
echo "install vmware vix-disklib-lib"
echo "press key"
read line
$AQI/vmware-vix-disklib-distrib/vmware-install.pl

echo ""
echo "dont forget to open ssh port on your esxi server!"
echo "press key"
read line
